export const DOMAINS = [
	"Technology",
	"Education",
	"Finance",
	"Healthcare",
	"Retail",
	"Real Estate",
	"Agriculture",
	"Manufacturing",
	"Transportation",
	"Logistics",
	"Hospitality",
	"Entertainment",
	"Media",
	"Telecommunications",
	"Energy",
	"Utilities",
	"Construction",
	"Automotive",
	"Government",
	"Non-profit",
	"Others",
]

export const mapDefaults = {
	zoom: 2,
}

export const locationsRecord: Record<string, string> = {
	"IN": "India",
  "IN-AN": "Andaman and Nicobar Islands",
  "IN-AP": "Andhra Pradesh",
  "IN-AR": "Arunachal Pradesh",
  "IN-AS": "Assam",
  "IN-BR": "Bihar",
  "IN-CH": "Chandigarh",
  "IN-CT": "Chhattisgarh",
  "IN-DN": "Dadra and Nagar Haveli",
  "IN-DD": "Daman and Diu",
  "IN-DL": "Delhi",
  "IN-GA": "Goa",
  "IN-GJ": "Gujarat",
  "IN-HR": "Haryana",
  "IN-HP": "Himachal Pradesh",
  "IN-JK": "Jammu and Kashmir",
  "IN-JH": "Jharkhand",
  "IN-KA": "Karnataka",
  "IN-KL": "Kerala",
  "IN-LD": "Lakshadweep",
  "IN-MP": "Madhya Pradesh",
  "IN-MH": "Maharashtra",
  "IN-MN": "Manipur",
  "IN-ML": "Meghalaya",
  "IN-MZ": "Mizoram",
  "IN-NL": "Nagaland",
  "IN-OR": "Odisha",
  "IN-PY": "Puducherry",
  "IN-PB": "Punjab",
  "IN-RJ": "Rajasthan",
  "IN-SK": "Sikkim",
  "IN-TN": "Tamil Nadu",
  "IN-TG": "Telangana",
  "IN-TR": "Tripura",
  "IN-UP": "Uttar Pradesh",
  "IN-UT": "Uttarakhand",
  "IN-WB": "West Bengal",
	"US-AL": "Alabama",
"US-AK": "Alaska",
"US-AZ": "Arizona",
"US-AR": "Arkansas",
"US-CA": "California",
"US-CO": "Colorado",
"US-CT": "Connecticut",
"US-DE": "Delaware",
"US-DC": "District of Columbia",
"US-FL": "Florida",
"US-GA": "Georgia",
"US-HI": "Hawaii",
"US-ID": "Idaho",
"US-IL": "Illinois",
"US-IN": "Indiana",
"US-IA": "Iowa",
"US-KS": "Kansas",
"US-KY": "Kentucky",
"US-LA": "Louisiana",
"US-ME": "Maine",
"US-MD": "Maryland",
"US-MA": "Massachusetts",
"US-MI": "Michigan",
"US-MN": "Minnesota",
"US-MS": "Mississippi",
"US-MO": "Missouri",
"US-MT": "Montana",
"US-NE": "Nebraska",
"US-NV": "Nevada",
"US-NH": "New Hampshire",
"US-NJ": "New Jersey",
"US-NM": "New Mexico",
"US-NY": "New York",
"US-NC": "North Carolina",
"US-ND": "North Dakota",
"US-OH": "Ohio",
"US-OK": "Oklahoma",
"US-OR": "Oregon",
"US-PA": "Pennsylvania",
"US-RI": "Rhode Island",
"US-SC": "South Carolina",
"US-SD": "South Dakota",
"US-TN": "Tennessee",
"US-TX": "Texas",
"US-UT": "Utah",
"US-VT": "Vermont",
"US-VA": "Virginia",
"US-WA": "Washington",
"US-WV": "West Virginia",
"US-WI": "Wisconsin",
"US-WY": "Wyoming",
  } as const;